### ISSUE TITLE
AP7900 Support question

### ISSUE THREAD

**Issue by mac067783** [ecoen66/homebridge-platform-raritanpdu#3]
First off, Thank you for creating this plugin! Just wanted to give you some feedback that this plug in works for the AP7900, pretty well even though, the system starts up and runs fine, but I get this error...not saying its something you have to address, but figured I'd throw it out to you incase you were interested in expanding the compatibility list...I'm happy to test for you if you would like. 

[2/26/2021, 9:44:34 AM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 4 status.
(node:87422) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:87422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 219)

**Comment by ecoen66** [comment]
Can you try updating to v 0.1.2, and enable the debug config option for the plugin within the plugin settings in the homebridge Config UI?  This enables additional logging output for the plugin.

You should see additional information for the PDU, like:
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] There are 16 outlets.
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] PDU name SDA PoV PDU.
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] PDU model number AP7931.
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] PDU serial number ZA0439005838.
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] PDU firmware version B2.

Also helpful would be the debug logging of results when the plugin gathers the outlet data:
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names= [
  'SDA PoV Edge2',       'SDA PoV Edge 1',
  'SDA PoV CP-Border 2', 'SDA PoV CP-Border1',
  'SDA PoV WLC',         'SDA PoV Layer2 2960',
  'SDA PoV Fusion 4431', 'SDA PoV ASA5508',
  'SDA PoV Client2',     'SDA PoV Client1',
  'Outlet 11',           'Outlet 12',
  'Outlet 13',           'Outlet 14',
  'Outlet 15',           'Outlet 16'
]
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 0 = SDA PoV Edge2
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 1 = SDA PoV Edge 1
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 2 = SDA PoV CP-Border 2
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 3 = SDA PoV CP-Border1
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 4 = SDA PoV WLC
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 5 = SDA PoV Layer2 2960
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 6 = SDA PoV Fusion 4431
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 7 = SDA PoV ASA5508
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 8 = SDA PoV Client2
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 9 = SDA PoV Client1
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 10 = Outlet 11
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 11 = Outlet 12
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 12 = Outlet 13
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 13 = Outlet 14
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 14 = Outlet 15
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU names 15 = Outlet 16
[2/26/2021, 10:18:16 AM] [LAB Platform PDU] SDA PoV PDU Successfully loaded outlet names:  SDA PoV Edge2, SDA PoV Edge 1, SDA PoV CP-Border 2, SDA PoV CP-Border1, SDA PoV WLC, SDA PoV Layer2 2960, SDA PoV Fusion 4431, SDA PoV ASA5508, SDA PoV Client2, SDA PoV Client1, Outlet 11, Outlet 12, Outlet 13, Outlet 14, Outlet 15, Outlet 16

Please post your results here.
Thanks!

**Comment by mac067783** [comment]
Sure, Here you go: 
[2/26/2021, 1:21:35 PM] [MediaPDU] Initializing Platform PDU platform...
[2/26/2021, 1:21:35 PM] [MediaPDU] Finished initializing platform: MediaPDU
[2/26/2021, 1:21:35 PM] [MediaPDU] Restoring accessory from cache: 6903338a-853b-4dd5-ba24-75c0b65788c7 LOWER-LEVEL-PDU
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 0 Outlet 0
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 1 Outlet 1
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 2 Outlet 2
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 3 Outlet 3
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 4 Outlet 4
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 5 Outlet 5
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 6 Outlet 6
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU serviceName for 7 Outlet 7
[2/26/2021, 1:21:35 PM] [MediaPDU] LOWER-LEVEL-PDU Outlet OIDs for names [
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.1',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.2',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.3',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.4',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.5',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.6',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.7',
  '1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.8'
]
[2/26/2021, 1:21:36 PM] [MediaPDU] Executed didFinishLaunching callback
[2/26/2021, 1:21:36 PM] [MediaPDU] Opened SNMP session.
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names= [ 'PowerAmp&AP Express', '2', '3', '4', '5', '6', '7', '8' ]
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 0 = PowerAmp&APExpress
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 1 = 2
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 2 = 3
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 3 = 4
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 4 = 5
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 5 = 6
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 6 = 7
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU names 7 = 8
[2/26/2021, 1:21:36 PM] [MediaPDU] LOWER-LEVEL-PDU Successfully loaded outlet names:  PowerAmp&APExpress, 2, 3, 4, 5, 6, 7, 8
[2/26/2021, 1:21:36 PM] [MediaPDU] Manufacturer varbind returned APC Web/SNMP Management Card (MB:v3.9.2 PF:v3.7.0 PN:apc_hw02_aos_370.bin AF1:v3.7.0 AN1:apc_hw02_rpdu_370.bin MN:AP7900 HR:B2 SN: ZA0937003837 MD:09/09/2009) 
[2/26/2021, 1:21:36 PM] [MediaPDU] device.manufacturer =  APC
[2/26/2021, 1:21:36 PM] [MediaPDU] There are 8 outlets.
[2/26/2021, 1:21:36 PM] [MediaPDU] PDU name LOWER-LEVEL-PDU.
[2/26/2021, 1:21:36 PM] [MediaPDU] PDU model number AP7900.
[2/26/2021, 1:21:36 PM] [MediaPDU] PDU firmware version B2.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 0.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 1.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 6.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 2.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 3.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 5. 
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 4. 
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 7. 
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 0 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 1 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 6 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 6 status.
(node:40955) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 2 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 3 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 5 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 5 status.
(node:40955) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:40955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 4 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 7 is true.
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 7 status.
(node:40955) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:40955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[2/26/2021, 1:21:37 PM] [MediaPDU] LOWER-LEVEL-PDU Calling getWatts 253

**Comment by ecoen66** [comment]
Wow!  That's odd... So, it is receiving the status of Outlet 6 and doing a Callback with that value, while also catching an error from the SNMP request for Outlet 6 status and doing a Callback with the error.  To my knowledge, it should be an either or scenario.  I honestly wouldn't know where to start to troubleshoot that without having the device in my lab.  If I get my hands on one, or a Cisco version of the same, I'll update the plugin.

**Comment by mac067783** [comment]
Yeah, very weird indeed:  It looks like it is doing it with other outlets too, not just number 6...wonder if it's because it's on an older firmware. 


[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 0.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 1.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 2.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 4.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 3.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 7.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 5.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 6.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 0 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 1 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 2 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 4 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 4 status.
(node:41580) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:41580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 3 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 7 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 7 status.
(node:41580) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:41580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 5 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 6 is true.
[2/26/2021, 3:23:33 PM] [MediaPDU] LOWER-LEVEL-PDU Calling getWatts 242
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 0.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 1.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 2.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 4.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 3.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 7.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 5.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 6.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 0 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 1 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 2 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 4 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 4 status.
(node:41580) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:41580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 3 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 7 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 7 status.
(node:41580) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:41580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 5 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 6 is true.
[2/26/2021, 3:26:50 PM] [MediaPDU] LOWER-LEVEL-PDU Calling getWatts 242
[2/26/2021, 3:26:51 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 1559 exceeded maximum of 500. See https://git.io/JtMGR for more info.
[2/26/2021, 3:26:51 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 1559 exceeded maximum of 500. See https://git.io/JtMGR for more info.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 0.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 1.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 2.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 4.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 3.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 7.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 5.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Retrieving socket 6.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 0 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 1 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 2 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 4 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 4 status.
(node:41580) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:41580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 3 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 7 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Error retrieving socket 7 status.
(node:41580) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-platform-pdu/src/platformAccessory.ts:189:9
(node:41580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 5 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Socket 6 is true.
[2/26/2021, 3:28:36 PM] [MediaPDU] LOWER-LEVEL-PDU Calling getWatts 242

**Comment by ecoen66** [comment]
The age of the firmware is a possibility.  Here's my APC PDU stats:


### Hardware Factory
Model Number: | AP7931
Serial Number: | ZA0439005838
Hardware Revision: | B2
Manufacture Date: | 09/22/2004


### Application Module:
Name: | rpdu
Version: | v3.9.2
Date: | 07/07/2016
Time: | 10:40:30


### APC OS (AOS):
Name: | aos
Version: | v3.9.2
Date: | 07/06/2016
Time: | 15:12:05

**Comment by mac067783** [comment]
Hardware Factory
 
Model Number: | AP7900
Hardware Revision: | B2
Manufacture Date: | 09/09/2009

Application Module

Name:rpdu
Version:v3.7.0
Date:01/13/2009
Time:15:30:40
 
APC OS

Name: | aos
Version: | v3.7.0
Date: | 01/13/2009
Time: | 14:17:08

**Comment by mac067783** [comment]
I've updated to AOS v3.9.0 and rpdu v3.7.4 and am still getting the same error message...I'm using SNMP v1 not sure if that matters. Could you add a 1 sec wait between outlet status polling or add it as a variable...since your PDU seems to be newer, I wonder if it is trying to flood my older network management card and it's getting tripped up...

**Comment by mac067783** [comment]
I've gone through and updated all of my outlets to have "Word" values for the outlet configurations(including the "URL")

**Comment by mac067783** [comment]
I've gone through and renamed my outlets to word values instead of numerical values, as well as changing the SNMP user to have Write+ instead of Write, and that seems to have fixed my issue after I cleared the cache for that accessory.  No more errors are popping up in the console. 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/58493983/110132949-b4b28a00-7d99-11eb-9764-6bfab631883d.png">

**Comment by ecoen66** [comment]
That's great news!  Thanks for continuing to troubleshoot the issue.
